version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_volume:/root/.caddy
    environment:
      ACME_AGREE: "true"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      DB_HOST: postgres
      DB_NAME: popbadge_production
      DB_USERNAME: postgres
      DB_PASSWORD: toor
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - public_sources:/app/public/sources

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: popbadge_production
      POSTGRES_PASSWORD: toor
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  caddy_volume:
  db_volume:
  public_sources:
