version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      DB_HOST: postgres
      DB_NAME: popbadge_production
      DB_USERNAME: postgres
      DB_PASSWORD: toor
    ports:
      - '80:3000'
    depends_on:
      - postgres
    networks:
      - pop-badge-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: popbadge_production
      POSTGRES_PASSWORD: toor
    networks:
      - pop-badge-network
    volumes:
      - db_volume:/var/lib/postgresql/data

networks:
  pop-badge-network:
    driver: bridge

volumes:
  db_volume:
