
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000

development:
  <<: *default
  host: "localhost"
  database: "popbadge_development"
  username: "popbadge"
  password: "LogeMan1234"

production:
  <<: *default
  host: "postgres"
  database: "popbadge_production"
  username: "postgres"
  password: "toor"
